kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  local:
    path: ./oc-mirror-metadata
mirror:
  platform:
    graph: true # Required for the OSUS ooperator
    architectures:
      - amd64
    channels:
    - name: stable-4.12
      minVersion: '4.12.28'
      maxVersion: '4.12.28'
      type: ocp
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.12
    packages:
    # ODF Packages
    - name: local-storage-operator
    - name: ocs-operator
    - name: odf-operator
    - name: mcg-operator
    - name: odf-csi-addons-operator
    - name: odr-cluster-operator
    - name: odr-hub-operator
    # OADP Packages
    - name: redhat-oadp-operator
    # OCP Update Service
    - name: cincinnati-operator
    # RHACM Packages
    - name: advanced-cluster-management
    - name: multicluster-engine
    - name: klusterlet-product
    # RHACS packages
    - name: rhacs-operator
    # Compliance Operator
    - name: compliance-operator
    # Cert Manager
    - name: openshift-cert-manager-operator
    # RH AAP
    - name: ansible-automation-platform-operator
    - name: ansible-cloud-addons-operator
    # RH Gitops: Broken https://issues.redhat.com/projects/GITOPS/issues/GITOPS-2991?filter=allopenissues
    #- name: openshift-gitops-operator
    # RH Pipelines
    - name: openshift-pipelines-operator-rh
    # OCP Logging
    - name: cluster-logging
    - name: loki-operator
    # RH Dist Tracing - Tempo Does not work disconnected on 4.12, seems fixed in 4.1
    - name: jaeger-product
    - name: opentelemetry-product
    - name: tempo-product
    - name: elasticsearch-operator
    # Red Hat Service Mesh
    - name: servicemeshoperator
    # Network Observability Operator
    - name: netobserv-operator
  - catalog: registry.redhat.io/redhat/community-operator-index:v4.12
    packages:
    # ESO
    - name: external-secrets-operator
  additionalImages:
  # Generic tools
  - name: registry.redhat.io/ubi8/ubi:latest
  - name: registry.redhat.io/ubi9/ubi:latest
  - name: registry.redhat.io/rhel8/support-tools:latest
  - name: registry.redhat.io/rhel9/support-tools:latest
  - name: registry.redhat.io/openshift4/network-tools-rhel8:latest
  # Must gather tools: https://docs.openshift.com/container-platform/4.12/support/gathering-cluster-data.html#gathering-data-specific-features_gathering-cluster-data
  - name: registry.redhat.io/openshift4/ose-must-gather:v4.12
  - name: registry.redhat.io/openshift4/ose-must-gather:latest
  - name: registry.redhat.io/odf4/odf-must-gather-rhel9:v4.13.0
  - name: registry.redhat.io/openshift4/ose-local-storage-mustgather-rhel8:latest
  - name: registry.redhat.io/oadp/oadp-mustgather-rhel8:v1.2
  - name: registry.redhat.io/multicluster-engine/must-gather-rhel8:v2.3.0
  - name: registry.redhat.io/rhacm2/acm-must-gather-rhel8:v2.8.0-29
  #- name: registry.redhat.io/ansible-automation-platform-24/aap-must-gather-rhel8:latest
  #- name: registry.redhat.io/ansible-automation-platform-23/aap-must-gather-rhel8:latest
  - name: registry.redhat.io/openshift-logging/cluster-logging-rhel8-operator:v5.7
  #- name: registry.redhat.io/openshift-gitops-1/must-gather-rhel8:v1.9.0
  # Ansible EE to run playbooks
  - name: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:1.0.0
  helm: {}
